module.exports = {
  ERROR_CODES: {
    PRESIGN_ERROR: 'PRESIGN_ERROR',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    CORRUPT_FILE: 'CORRUPT_FILE',
    REQUEST_FAILED: 'REQUEST_FAILED',
    FILE_READ_ERROR: 'FILE_READ_ERROR',
    FILE_PARSE_ERROR: 'FILE_PARSE_ERROR',
    NO_FILE_FOUND: 'NO_FILE_FOUND',
    PARSER_ERROR: 'PARSER_ERROR',
    S3_WRITE_ERROR: 'S3_WRITE_ERROR',
  },
};
  